# Generated by Django 5.0.6 on 2024-07-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0002_tipocuarto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocuarto',
            name='imagen',
            field=models.URLField(),
        ),
    ]
